default: &default
  adapter: mysql2
  #adapter: mysql2spatial
  username: root
  password: Jf99109Thunder
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: FindLoc_development

test:
  <<: *default
  database: FindLoc_test

production:
  <<: *default
  database: FindLoc_production
  username: FindLoc
  password: <%= ENV['FINDLOC_DATABASE_PASSWORD'] %>